#!/bin/bash
# Configure linuxMint - backups, workspaces, tiling, hot corners, icons on panel

# Create src directory
if [ -d ~/src ]; then
  printf '** WARNING: This system already has a ~/src directory. **\n'
  printf 'It may have been configured already. Continuing may break stuff. '
  printf 'Are you sure you want to continue? [y/n]'
  read CONTINUE
  if [ $CONTINUE != 'y' ]; then
    return
  fi
else
  mkdir ~/src
fi

# Prompt user for input: Do you want to update your bash and git aliases and add git branch to CLI
# Prompt user for input: Do you want to install all software?
# IF YES, run fileInstallation, or parts of it?
# store these to variables early, then make decisions for the user as script progresses.

# download and source supporting file, then edit .bashrc PS1 variable to display git branch
curl -L https://raw.github.com/git/git/master/contrib/completion/git-prompt.sh > ~/.git-prompt.sh
sed -i '1isource ~/.git-prompt.sh\n' ~/.bashrc
sed -i 's/($debian_chroot)}/($debian_chroot)}$(__git_ps1 "(%s)")/g' ~/.bashrc

# add git aliases to .gitconfig
cat << EOT >> ~/.gitconfig
[alias]
  co = checkout
  ci = commit
  st = status
  br = branch
  hist = log --pretty=format:\"%h %ad | %s%d [%an]\" --graph --date=short
EOT

## Add aliases to .bashrc
# TODO Do I need to CHMOD jiggety for security reasons?
# NOTE: must be non-root
# create .bash_aliases file and write aliases
if [ ! -f ~/.bash_aliases ]; then
  cat ~/src/jiggety/aliases >> ~/.bash_aliases
fi

# append .bash_aliases call to .bashrc
printf '\n# added by jiggety:\n' >> ~/.bashrc
printf '%s\n    %s\n%s\n' 'if [ -f ~/.bash_aliases ]; then' 'source ~/.bash_aliases' 'fi' >> ~/.bashrc


# UNCOMMENT THIS ONLY AFTER THIS SCRIPT RUNS fileInstallation
# This section must follow fileInstallation, so that a .atom dir exists
# if [ -d ~/.atom ]; then
#   printf "%s\n" "\"atom-workspace atom-text-editor\": {" \
#   "    \"ctrl-backspace\": \"editor:delete-to-previous-word-boundary\"," \
#   "    \"ctrl-delete\": \"editor:delete-to-next-word-boundary\"," \
#   "}" > ~/.atom/keymap.cson
# fi
